# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

variables:
- name: app_name
  value: angular-app

pool: NPM Test

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'

- script: |
    npm install --location=global @angular/cli
    npm install
    ng build --configuration=azure
  displayName: 'npm install and build'
  



