# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

variables:
- name: app_name
  value: angular-app

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'

- script: |
    npm install --location=global @angular/cli
    npm install
    ng build --configuration=azure
  displayName: 'npm install and build'
  
- script: |
    ls $(pwd)
    echo ---
    ls $(Build.SourcesDirectory)
    
    

- task: ArchiveFiles@2
  enabled: false
  inputs:
    rootFolderOrFile: '$(Agent.BuildDirectory)/dist/$(variables.app_name)'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

- script: |
    ls $(Build.ArtifactStagingDirectory)/

- task: AzureRmWebAppDeployment@4
  enabled: false
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'azure MAIC #1'
    appType: 'webAppLinux'
    WebAppName: 'angulartektest'
    packageForLinux: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    RuntimeStack: 'NODE|16-lts'
